---
title: "Bird data analysis"
author: "Kathina Müssig"
date: "12 Juni 2021"
output: pdf_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(echo = TRUE)
library(vegan)
```

```{r, include=FALSE}
bird<-read.csv("data/Bird_community.csv", sep=",", header=TRUE, row.names = 1)
bird[is.na(bird)] <- 0
env<-read.csv("data/bird_environment.csv", sep = ";", dec = ",", header = TRUE)
env[is.na(env)] <- 0

hist(rowSums(bird),
     col = "grey", # colors of bins
     main = "Bird Community Sampling", # plot title
     xlab = "Number of individuals") # x-axis title
```

```{r, include=FALSE}
# species richness

# rarefaction (to smalles species size in dataset) to make different sites comparable
# cause our sites were sampled in a similar manner in terms of sampling intensity we don't have to create rarefaction curves but species-accumulation-curve 
#-> how good was sampling to assess species richness? 
SAC <- specaccum(bird)
plot(SAC, xlab = "sampling plots", ylab = "species richness", main="species accumulation curve")

SAC_park <- specaccum(subset(bird, env$category == "park"))
SAC_fore <- specaccum(subset(bird, env$category == "forest"))

plot(SAC_park, xlab = "plots", ylab = "species richness", main="species accumulation curve")
plot(SAC_fore, xlab = "plots", ylab = "species richness", main="species accumulation curve", col="green", add = T)
legend("bottomright", legend = c("park","forest"), col = c("black","green"),lwd=1, bty = "n")
```

